//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulIdareSıstemıForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class İletisimFormu
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Ülke { get; set; }
        public string Konu { get; set; }
    }
}
