//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulIdareSıstemıForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OKULEntities1 : DbContext
    {
        public OKULEntities1()
            : base("name=OKULEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Banka> Banka { get; set; }
        public virtual DbSet<Calisan> Calisan { get; set; }
        public virtual DbSet<Ders> Ders { get; set; }
        public virtual DbSet<İletisimFormu> İletisimFormu { get; set; }
        public virtual DbSet<Ogrenci> Ogrenci { get; set; }
        public virtual DbSet<OgrenciDers> OgrenciDers { get; set; }
        public virtual DbSet<OkulYonetim> OkulYonetim { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Sube> Sube { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
